name: Jekyll diff
author: David Byrne
description: Diffs the built Jekyll site after a change, and comments the result back to GitHub
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'file-plus'
  color: 'green'
